import{a as g,S as b,i}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&l(p)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const w="48879708-f080042100b5dbafec10d9d0f",L="https://pixabay.com/api/";async function u(t,e=1){try{const a=new URLSearchParams({key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20,page:e}),{data:l}=await g.get(`${L}?${a}`);if(!l.hits.length)throw new Error("No images found for this query.");return l}catch(a){return console.error("Error fetching images:",a.message),{hits:[],totalHits:0}}}function m(t){return t.map(e=>`<a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
      <div class="info">
        <p class ="info-item">Likes <span class="info-amount">${e.likes}</span></p>
        <p class ="info-item">Views <span class="info-amount">${e.views}</span></p>
        <p class ="info-item">Comments <span class="info-amount">${e.comments}</span></p>
        <p class ="info-item">Downloads <span class="info-amount">${e.downloads}</span></p>
      </div>
    </a>`).join("")}const E=document.querySelector("#search-form"),d=document.querySelector(".gallery"),n=document.querySelector(".loader"),s=document.querySelector(".load-more"),h=new b(".gallery a");let f=1,c="";E.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements.searchQuery.value.trim(),!c){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}f=1,n.style.display="block",d.innerHTML="",s.style.display="none";try{const e=await u(c,f);if(n.style.display="none",e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query!",position:"topRight"});return}d.innerHTML=m(e.hits),h.refresh(),e.totalHits>20&&(s.style.display="block"),y()}catch{n.style.display="none",i.error({title:"Error",message:"An error occurred while fetching images!",position:"topRight"})}});s.addEventListener("click",async()=>{f+=1,n.style.display="block",s.disabled=!0;try{const t=await u(c,f);if(n.style.display="none",s.disabled=!1,t.hits.length===0){i.error({title:"Error",message:"No more images available.",position:"topRight"}),s.style.display="none";return}d.insertAdjacentHTML("beforeend",m(t.hits)),h.refresh(),t.hits.length<20&&(s.style.display="none",i.info({title:"End of results",message:"You've reached the end of the search results.",position:"topRight"})),y()}catch{n.style.display="none",s.disabled=!1,i.error({title:"Error",message:"An error occurred while fetching more images!",position:"topRight"})}});function y(){const t=d.querySelector(".gallery-item");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*3,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
